version: 2.1

x-job: &job
  docker:
    - image: cimg/python:3.7
  environment:
    REGISTRY_HOST: docker.cloudsmith.io
    REGISTRY_REPO: sturdy-waffle/build-images 
  steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Prepare Environment
        command: |
          echo "export TIME_TAG=`date +%Y%m%d`.$CIRCLE_BUILD_NUM" >> $BASH_ENV
          echo "export IMAGE_NAME=$REGISTRY_HOST/$REGISTRY_REPO/$CIRCLE_JOB" >> $BASH_ENV
    - run:
        name: Login to Cloudsmith
        command: echo "$REGISTRY_PASSWORD" | docker login $REGISTRY_HOST -u $REGISTRY_USERNAME --password-stdin
    - run:
        name: Pull Existing Image
        command: docker pull $IMAGE_NAME:latest || exit 0
    - run:
        name: Build Docker Image
        command: docker build --cache-from $IMAGE_NAME:latest -t $IMAGE_NAME:$TIME_TAG $CIRCLE_JOB/
    - run:
        name: Tag Docker Image
        command: docker tag $IMAGE_NAME:$TIME_TAG $IMAGE_NAME:latest
    - run:
        name: Push Docker Image
        command: |
          docker push $IMAGE_NAME:$TIME_TAG
          docker push $IMAGE_NAME:latest

jobs:
  debian-build:
    <<: *job

workflows:
  version: 2
  build_and_publish:
    jobs:
      - debian-build
